// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static struct sensor_settings s_sensor_settings = {42, 42, 42};
void glue_get_sensor_settings(struct sensor_settings *data) {
  *data = s_sensor_settings;  // Sync with your device
}
void glue_set_sensor_settings(struct sensor_settings *data) {
  s_sensor_settings = *data; // Sync with your device
}

static struct settings s_settings = {0, "192.168.1.134"};
void glue_get_settings(struct settings *data) {
  *data = s_settings;  // Sync with your device
}
void glue_set_settings(struct settings *data) {
  s_settings = *data; // Sync with your device
}

static struct sensor_read s_sensor_read = {false, false, 100, 20};
void glue_get_sensor_read(struct sensor_read *data) {
  *data = s_sensor_read;  // Sync with your device
}
void glue_set_sensor_read(struct sensor_read *data) {
  s_sensor_read = *data; // Sync with your device
}
